"""
AUTO-GENERATED by gen_capability_surfaces.py from AitherOS/config/capability-manifest.yaml -- do
not edit. Regenerate with: python AitherOS/dev/tools/gen_capability_surfaces.py

One SlashCommand subclass per capability with a `cli:` surface; the
shell's PluginRegistry globs builtins/*.py and registers every
SlashCommand subclass automatically — zero loader changes.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from adk.shell.plugins import SlashCommand

_REPO_ROOT = Path(__file__).resolve().parents[5]

class BootCodesCommand(SlashCommand):
    name = 'boot-codes'
    aliases = ['bootcodes', 'mint-boot']
    description = 'Boot Codes - mint codes for the aitherium.com boot gate'

    def __init__(self) -> None:
        super().__init__(
            name='boot-codes',
            description='Boot Codes - mint codes for the aitherium.com boot gate',
            aliases=['bootcodes', 'mint-boot'],
        )

    async def run(self, args: List[str], ctx: Dict[str, Any]) -> Optional[str]:
        """Dispatch to the declared tool, streaming its output back."""
        tool = _REPO_ROOT / 'AitherOS/dev/tools/mint_boot_code.py'
        if not tool.is_file():
            return f"tool not found: {tool} — is this a repo checkout?"
        proc = await asyncio.create_subprocess_exec(
            sys.executable, str(tool), *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(_REPO_ROOT),
        )
        out, err = await proc.communicate()
        text = out.decode('utf-8', errors='replace') + err.decode('utf-8', errors='replace')
        return text.strip() or f"(exit {proc.returncode})"
