"""Every adk toolpack that registers tools ships a TRACKED ``.toolpack.yaml``.

The loader (``adk.tool_pack_loader``) only discovers a directory that contains
``.toolpack.yaml``. Measured 2026-09-30 (D-17/18): the awrise pack landed as
``__init__.py`` + ``tools.py`` while its manifest stayed an untracked file in
one worktree, so every installed and PyPI adk printed ``37 False`` for
``'awrise' in loader._manifests`` -- the whole pack was dead, and its own test
only failed on machines that happened to lack the stray file.

The check reads ``git ls-files`` when the package sits in a git checkout (the
file must be TRACKED, not merely present), and the disk otherwise.

    python awdk/tests/test_toolpack_manifests_tracked.py            # 0 clean, 1 violation, 2 cannot judge
    python awdk/tests/test_toolpack_manifests_tracked.py --self-test
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

TOOLPACKS = Path(__file__).resolve().parents[1] / "adk" / "toolpacks"

#: Pack dirs that register tools but are deliberately NOT loader-discovered.
#: Every entry names a debt id or the reason; printed on every run.
ALLOWLIST = {
    "codegen_bridge": "D-2718: register() but no manifest; nothing discovers it",
    "publish_preflight": "D-2718: reached directly by `adk publish-preflight`, not the loader",
    "svc_*": "D-2718: generated by _service_spec without a manifest",
}


def _allowed(name: str) -> bool:
    for pat in ALLOWLIST:
        if pat.endswith("*") and name.startswith(pat[:-1]):
            return True
        if name == pat:
            return True
    return False


def _files(root: Path) -> "tuple[set, str]":
    """Relative posix paths under ``root`` and where they came from."""
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "ls-files", "--full-name", "."],
            capture_output=True, text=True, timeout=60)
        top = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        out = top = None
    if out is not None and out.returncode == 0 and top.returncode == 0 and out.stdout.strip():
        base = Path(top.stdout.strip()).resolve()
        rel_root = root.resolve().relative_to(base).as_posix()
        files = {ln[len(rel_root) + 1:] for ln in out.stdout.splitlines()
                 if ln.startswith(rel_root + "/")}
        return files, "git ls-files"
    return {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()}, "disk"


def _registers(root: Path, pack: str, files: set) -> bool:
    if f"{pack}/tools.py" in files:
        return True
    init = root / pack / "__init__.py"
    if f"{pack}/__init__.py" in files and init.exists():
        return "def register(" in init.read_text(encoding="utf-8", errors="replace")
    return False


def violations(root: Path) -> "tuple[list, str]":
    files, source = _files(root)
    packs = sorted({f.split("/", 1)[0] for f in files if "/" in f})
    bad = []
    for pack in packs:
        if pack.startswith(("_", ".")) or _allowed(pack):
            continue
        if _registers(root, pack, files) and f"{pack}/.toolpack.yaml" not in files:
            bad.append(pack)
    return bad, source


def test_every_registering_pack_has_a_tracked_manifest():
    print("allowlist:", ALLOWLIST)
    bad, source = violations(TOOLPACKS)
    assert not bad, (f"toolpacks with tools but no .toolpack.yaml ({source}): {bad} "
                     "-- the loader cannot discover them; commit the manifest")


def test_loader_discovers_awrise():
    from adk.tool_pack_loader import ToolPackLoader
    loader = ToolPackLoader(extra_dirs=[TOOLPACKS], enforce_entitlements=False)
    found = loader.discover()
    assert "awrise" in found


def self_test() -> int:
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "good").mkdir()
        (root / "good" / "tools.py").write_text("x = 1\n", encoding="utf-8")
        (root / "good" / ".toolpack.yaml").write_text("id: good\n", encoding="utf-8")
        (root / "dead").mkdir()
        (root / "dead" / "__init__.py").write_text("def register(a):\n    pass\n",
                                                   encoding="utf-8")
        (root / "svc_x").mkdir()
        (root / "svc_x" / "tools.py").write_text("x = 1\n", encoding="utf-8")
        bad, _ = violations(root)
    ok = bad == ["dead"]
    print("self-test", "ok" if ok else f"FAILED: {bad}")
    return 0 if ok else 1


def main(argv: "list[str] | None" = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--self-test" in argv:
        return self_test()
    print("allowlist:", ALLOWLIST)
    if not TOOLPACKS.is_dir():
        print(f"DEAD: {TOOLPACKS} not found")
        return 2
    bad, source = violations(TOOLPACKS)
    if bad:
        print(f"FAIL ({source}): packs with tools but no tracked .toolpack.yaml: {bad}")
        return 1
    print(f"ok ({source}): every registering pack has a manifest")
    return 0


if __name__ == "__main__":
    sys.exit(main())
