"""Quadlet/Podman backend for addon container management.

Runs addons as **first-class systemd units** via Podman Quadlet instead of a
docker daemon. Enabling an addon writes a ``.container`` unit into the user
Quadlet dir (``~/.config/containers/systemd/``), runs ``systemctl --user
daemon-reload`` (which makes systemd's Quadlet generator translate it into a
``.service``), and starts it. The agent then manages it natively:
``systemctl --user restart aitheros-addon-<id>``.

Rootless by default (the ``aither`` user with linger). No daemon, no socket.

Mirrors adk/addon_docker.py's surface so AddonManager can dispatch to either.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

log = logging.getLogger("adk.addon_quadlet")

_NETWORK = "aitheros.network"


def _quadlet_dir() -> Path:
    """User Quadlet directory (override with AITHER_QUADLET_DIR for tests)."""
    d = os.environ.get("AITHER_QUADLET_DIR")
    if d:
        return Path(d)
    return Path.home() / ".config" / "containers" / "systemd"


def unit_base(addon_id: str) -> str:
    """systemd/Quadlet base name for an addon (file is <base>.container,
    service is <base>.service)."""
    return f"aitheros-addon-{addon_id}"


def _podman() -> str:
    return os.environ.get("AITHER_PODMAN", "podman")


def render_quadlet(manifest: Dict[str, Any]) -> str:
    """Render a Podman Quadlet ``.container`` unit from an addon manifest.

    Reuses the conventions of the platform's systemd unit generator
    (Network/health/deps), driven by the addon manifest schema (image,
    default_port, env_defaults, volumes, health_check, dependencies).
    """
    addon_id = manifest["id"]
    base = unit_base(addon_id)
    image = manifest.get("image", "")
    port = manifest.get("default_port")
    desc = manifest.get("description", f"AitherOS addon {addon_id}").strip()
    env = manifest.get("env_defaults", {}) or {}
    volumes = manifest.get("volumes", []) or []
    hc = manifest.get("health_check", {}) or {}
    deps = manifest.get("dependencies", []) or []

    after = [f"{unit_base(d)}.service" for d in deps]

    lines: List[str] = [
        "# Auto-generated by adk/addon_quadlet.py — DO NOT EDIT MANUALLY",
        f"# Addon: {addon_id}",
        "",
        "[Unit]",
        f"Description={desc.splitlines()[0] if desc else addon_id}",
    ]
    if after:
        lines.append(f"After={' '.join(after)}")
        lines.append(f"Requires={' '.join(after)}")
    lines += [
        "",
        "[Container]",
        f"Image={image}",
        f"ContainerName={base}",
        "AutoUpdate=registry",
        f"Network={_NETWORK}",
    ]
    if port:
        lines.append(f"PublishPort={port}:{port}")
    for k, v in env.items():
        lines.append(f"Environment={k}={v}")
    # Volumes: addon manifest uses [{name, path}] — bind under the user's data dir
    # (rootless-friendly; %h is expanded by systemd to the user's home).
    for vol in volumes:
        name = vol.get("name") if isinstance(vol, dict) else None
        path = vol.get("path") if isinstance(vol, dict) else None
        if name and path:
            lines.append(f"Volume=%h/.local/share/aitheros/{addon_id}/{name}:{path}:Z")
    if port:
        hpath = hc.get("path", "/health")
        lines.append(f"HealthCmd=curl -sf http://localhost:{port}{hpath} || exit 1")
        lines.append("HealthInterval=30s")
        lines.append("HealthRetries=3")
        lines.append("HealthStartPeriod=30s")

    lines += [
        "",
        "[Service]",
        "Restart=on-failure",
        "RestartSec=10",
        "TimeoutStartSec=120",
        "",
        "[Install]",
        "WantedBy=default.target",
    ]
    return "\n".join(lines) + "\n"


def write_unit(addon_id: str, content: str) -> Path:
    """Write the Quadlet unit file and return its path."""
    qdir = _quadlet_dir()
    qdir.mkdir(parents=True, exist_ok=True)
    path = qdir / f"{unit_base(addon_id)}.container"
    path.write_text(content, encoding="utf-8")
    return path


def _systemctl_user(*args: str, timeout: int = 60) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["systemctl", "--user", *args],
        capture_output=True, text=True, timeout=timeout,
    )


def daemon_reload() -> None:
    _systemctl_user("daemon-reload")


def start_quadlet(manifest: Dict[str, Any]) -> Dict[str, Any]:
    """Write the unit, reload, and start it. Returns {unit, service, endpoint}.

    Raises RuntimeError on a failed start so AddonManager records the error.
    """
    if not shutil.which(_podman()):
        raise RuntimeError(f"{_podman()} not found on PATH")
    addon_id = manifest["id"]
    base = unit_base(addon_id)
    write_unit(addon_id, render_quadlet(manifest))
    daemon_reload()
    res = _systemctl_user("start", f"{base}.service")
    if res.returncode != 0:
        raise RuntimeError(res.stderr.strip() or f"systemctl start {base} failed")
    port = manifest.get("default_port", 8000)
    return {"unit": f"{base}.container", "service": f"{base}.service",
            "endpoint": f"http://localhost:{port}"}


def stop_quadlet(addon_id: str) -> None:
    """Stop the unit and remove its Quadlet file."""
    base = unit_base(addon_id)
    try:
        _systemctl_user("stop", f"{base}.service")
    except Exception as e:  # noqa: BLE001
        log.warning("stop %s failed: %s", base, e)
    unit_path = _quadlet_dir() / f"{base}.container"
    if unit_path.exists():
        unit_path.unlink()
    try:
        daemon_reload()
    except Exception as e:  # noqa: BLE001
        log.debug("daemon-reload after stop failed: %s", e)


def quadlet_health(addon_id: str) -> Dict[str, Any]:
    """Return status via systemctl --user is-active."""
    base = unit_base(addon_id)
    try:
        res = _systemctl_user("is-active", f"{base}.service")
        active = res.stdout.strip()
        return {"name": base, "status": active, "running": active == "active"}
    except Exception as e:  # noqa: BLE001
        return {"name": base, "status": "error", "running": False, "error": str(e)}


def quadlet_logs(addon_id: str, tail: int = 100) -> str:
    base = unit_base(addon_id)
    try:
        res = subprocess.run(
            ["journalctl", "--user", "-u", f"{base}.service", "-n", str(tail), "--no-pager"],
            capture_output=True, text=True, timeout=15,
        )
        return res.stdout
    except Exception as e:  # noqa: BLE001
        return f"Error reading logs: {e}"


def list_addon_units(prefix: str = "aitheros-addon-") -> List[Dict[str, Any]]:
    """List addon Quadlet units present in the user Quadlet dir."""
    out = []
    qdir = _quadlet_dir()
    if not qdir.is_dir():
        return out
    for p in sorted(qdir.glob(f"{prefix}*.container")):
        addon_id = p.stem[len(prefix):]
        out.append({"addon_id": addon_id, "unit": p.name,
                    **quadlet_health(addon_id)})
    return out
