"""
AitherShell Crash Reporter (Python ADK)
=========================================

Catches unhandled exceptions in the CLI, prompts the user to send
an error report, and submits it via Genesis /feedback endpoint or
gh CLI as fallback. Creates GitHub issues automatically.
"""

import json
import os
import platform
import subprocess
import sys
import traceback
from datetime import datetime, timezone
from typing import Optional

GENESIS_URL = os.environ.get("AITHER_GENESIS_URL", "http://localhost:8001")
GITHUB_REPO = "Aitherium/AitherOS"
SUPPORT_URL = "https://demo.aitherium.com/support"
VERSION = "1.3.0"

_current_command: str = ""


def set_current_command(cmd: str) -> None:
    """Set the current command context for crash reports."""
    global _current_command
    _current_command = cmd


def _detect_gpu() -> Optional[str]:
    """Detect GPU (best-effort)."""
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader"],
            timeout=3,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        return out or None
    except Exception:
        return None


def _build_report(exc: BaseException, source: str = "command") -> dict:
    """Build a structured crash report."""
    import psutil
    ram_gb = round(psutil.virtual_memory().total / (1024**3))
    cpu_info = platform.processor() or "unknown"

    tb = "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))
    title = f"[AitherShell Crash] {str(exc)[:120]}"

    return {
        "title": title,
        "error_type": type(exc).__name__,
        "message": str(exc),
        "stack": tb,
        "context": {
            "command": _current_command or None,
            "version": VERSION,
            "platform": sys.platform,
            "arch": platform.machine(),
            "os_release": platform.release(),
            "python_version": platform.python_version(),
            "hostname": platform.node(),
            "ram_gb": ram_gb,
            "cpu": cpu_info,
            "gpu": _detect_gpu(),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    }


def _format_issue_body(report: dict) -> str:
    """Format as GitHub issue Markdown."""
    ctx = report["context"]
    cmd_line = f'**Command**: `{ctx["command"]}`\n' if ctx.get("command") else ""
    gpu_line = f'| GPU | {ctx["gpu"]} |' if ctx.get("gpu") else "| GPU | None detected |"

    return f"""## Automatic Error Report

**Source**: AitherShell ADK v{ctx["version"]}
**Timestamp**: {ctx["timestamp"]}
{cmd_line}
### Error
```
{report["error_type"]}: {report["message"]}
```

### Stack Trace
```
{report["stack"]}
```

### Environment
| Field | Value |
|-------|-------|
| Platform | {ctx["platform"]} {ctx["arch"]} |
| OS | {ctx["os_release"]} |
| Python | {ctx["python_version"]} |
| RAM | {ctx["ram_gb"]} GB |
| CPU | {ctx["cpu"]} |
{gpu_line}

---
*Auto-generated by AitherShell crash reporter*"""


def _ask_confirm(prompt: str) -> bool:
    """Ask Y/n with default Y. Non-interactive defaults to yes."""
    if not sys.stdin.isatty():
        return True
    try:
        answer = input(prompt).strip().lower()
        return answer in ("", "y", "yes")
    except (EOFError, KeyboardInterrupt):
        return False


def _submit_via_genesis(report: dict) -> Optional[str]:
    """Submit crash report via Genesis /feedback."""
    try:
        import urllib.request
        import urllib.error

        body = json.dumps({
            "rating": -1,
            "comment": _format_issue_body(report),
            "category": "Bug",
            "metadata": {
                "source": "aithershell-crash-reporter-adk",
                "type": "crash_report",
                "severity": "high",
                "error_type": report["error_type"],
                "title": report["title"],
                "stack_preview": "\n".join(report["stack"].split("\n")[:3]),
                "platform": report["context"]["platform"],
                "version": report["context"]["version"],
                "auto_report": True,
            },
        }).encode()

        req = urllib.request.Request(
            f"{GENESIS_URL}/feedback",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return data.get("feedback_id", "submitted")
    except Exception:
        return None


def _submit_via_gh_cli(report: dict) -> Optional[str]:
    """Create GitHub issue via gh CLI (fallback)."""
    try:
        body = _format_issue_body(report)
        title = report["title"].replace('"', '\\"')
        result = subprocess.check_output(
            ["gh", "issue", "create", "--repo", GITHUB_REPO,
             "--title", title, "--label", "bug,auto-report", "--body", body],
            timeout=15,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        return result  # Returns issue URL
    except Exception:
        return None


def handle_crash(exc: BaseException, source: str = "command") -> None:
    """Main crash handler — prompts user and submits report."""
    report = _build_report(exc, source)

    print("", file=sys.stderr)
    print(f"  \033[1;31mAitherShell encountered an error\033[0m", file=sys.stderr)
    print(f"  \033[31m{report['error_type']}: {report['message']}\033[0m", file=sys.stderr)
    if _current_command:
        print(f"  \033[2mCommand: {_current_command}\033[0m", file=sys.stderr)
    print("", file=sys.stderr)

    should_send = _ask_confirm(
        "  \033[33mSend error report to help us fix this? (Y/n)\033[0m "
    )

    if not should_send:
        print(f"  \033[2mNo report sent. Submit manually at:\033[0m", file=sys.stderr)
        print(f"  \033[36m{SUPPORT_URL}\033[0m", file=sys.stderr)
        print("", file=sys.stderr)
        return

    print("  \033[2mSubmitting error report...\033[0m", file=sys.stderr)
    result = _submit_via_genesis(report)

    if result:
        print(f"  \033[32mError report submitted ({result}).\033[0m", file=sys.stderr)
        print(f"  \033[2mOur team will investigate. Track at:\033[0m", file=sys.stderr)
        print(f"  \033[36m{SUPPORT_URL}\033[0m", file=sys.stderr)
    else:
        issue_url = _submit_via_gh_cli(report)
        if issue_url:
            print(f"  \033[32mGitHub issue created: {issue_url}\033[0m", file=sys.stderr)
        else:
            print(f"  \033[33mCould not submit automatically.\033[0m", file=sys.stderr)
            print(f"  \033[2mPlease report at:\033[0m", file=sys.stderr)
            print(f"  \033[36m{SUPPORT_URL}\033[0m", file=sys.stderr)
    print("", file=sys.stderr)


def install_crash_reporter() -> None:
    """Install sys.excepthook for automatic crash reporting."""
    _original_hook = sys.excepthook

    def _crash_hook(exc_type, exc_value, exc_tb):
        if exc_type is KeyboardInterrupt:
            # Don't report Ctrl+C
            _original_hook(exc_type, exc_value, exc_tb)
            return
        try:
            handle_crash(exc_value, source="uncaught")
        except Exception:
            pass  # Don't crash the crash reporter
        _original_hook(exc_type, exc_value, exc_tb)

    sys.excepthook = _crash_hook
