"""Sovereign AitherOS agents as harnesses — and group chat across them.

A coding harness (Claude Code) and a sovereign agent (Atlas, Lyra, Aeon, the
orchestrator) are different things wearing the same shape: you send a turn, you
get back text, thinking, tool calls and a completion. Modelling agents as
harnesses means one session list, one event stream and one UI drives both — you
can put Claude Code in tab 1 and Atlas in tab 2 and never notice the seam.

Transport is Genesis's unified SSE endpoint ``POST /chat/stream``, which its own
docstring calls "the ONE endpoint all clients should use". Its event vocabulary
(session_start / thinking / tool_call / tool_result / answer / complete) maps
almost one-to-one onto ours.

Group chat
----------
:class:`GroupSession` fans ONE user turn out to N agents concurrently and tags
every resulting event with the participant that produced it. That is the
"AitherAeon group chat" case: several sovereign agents in one room, each
answering in its own voice, interleaved in a single transcript rather than
serialized through a moderator.
"""

from __future__ import annotations

import json
import os
import threading
from typing import Any, Iterable, Optional

from adk.harnesses.events import (
    EventKind,
    HarnessEvent,
    error,
    notice,
    raw,
    text_delta,
    thinking_delta,
    tool_call,
    tool_result,
)
from adk.harnesses.session import HarnessSession, SessionState

GENESIS_URL = os.environ.get("AITHER_GENESIS_URL", "http://localhost:8001")
#: The host's own awdk loop (``adk serve``). The `awdk` harness relays here.
#: Genesis publishes no host port, so from the host daemon `aither` cannot
#: reach its default at all -- this address can, and it runs the loop the
#: ruler measures (plan of record 2026-09-21).
ADK_URL = os.environ.get("AITHER_ADK_URL", "http://127.0.0.1:9001")
STREAM_PATH = "/chat/stream"

#: The sovereign roster. Ids are what Genesis accepts as ``agent``; ``label`` and
#: ``role`` are what a human sees; ``persona`` is the line the daemon prepends to a
#: session's system prompt for the ``awdk`` harness (adk serve has no identity store
#: of its own). The block between the markers is GENERATED from the identity
#: registry by gen_sovereign_roster.py: edit the registry and regenerate, never this
#: list -- a hand-typed copy is how saga, vera and iris went missing (2026-09-21).
AGENT_ROSTER: list[dict[str, str]] = [
    # roster:begin -- GENERATED by gen_sovereign_roster.py from the identity registry;
    # do not hand-edit (regenerate; --check names drift). Rule: aither + aither's
    # children + every identity that declares dispatch_keywords.
    {
        "id": "aither",
        "label": "Aither",
        "role": "Sovereign AI and architect of AitherOS",
        "persona": (
            "Sovereign AI and architect of AitherOS \u2014 direct, no-nonsense, "
            "technically authoritative. Orchestrates all agents, delegates with "
            "precision, provides support with substance not ceremony."
        ),
    },
    {
        "id": "aeon",
        "label": "Aeon",
        "role": "Primary social presence",
        "persona": "Primary social presence - social engagement + Aither crossposting",
    },
    {
        "id": "aeros",
        "label": "Aeros",
        "role": "Communications Elemental",
        "persona": (
            "Communications Elemental \u2014 email delivery, notifications, webhooks, API "
            "integrations, message routing, channel bridging. The air that carries "
            "messages between agents, services, and the outside world."
        ),
    },
    {
        "id": "athena",
        "label": "Athena",
        "role": "Security analysis",
        "persona": (
            "Security analysis, vulnerability scanning, code auditing, threat "
            "modeling, compliance review"
        ),
    },
    {
        "id": "atlas",
        "label": "Atlas",
        "role": "Platform Brain",
        "persona": (
            "Platform Brain \u2014 observability, health monitoring, tri-agent "
            "coordination (Atlas+Lyra+Demiurge), roadmap, delegation, executive "
            "reporting, GitHub ops, cloud GPU deployment, compute pool management, "
            "BusinessPilot operations, tenant onboarding, billing, GPU marketplace"
        ),
    },
    {
        "id": "automation",
        "label": "Automation",
        "role": "PowerShell automation",
        "persona": (
            "PowerShell automation, script orchestration, IDI infrastructure "
            "management, OpenTofu provisioning, and system administration via "
            "AitherZero"
        ),
    },
    {
        "id": "demiurge",
        "label": "Demiurge",
        "role": "Code implementation",
        "persona": (
            "Code implementation, review, refactoring, feature shipping via GitHub "
            "PRs"
        ),
    },
    {
        "id": "hera",
        "label": "Hera",
        "role": "Head of Marketing & Growth",
        "persona": (
            "Head of Marketing & Growth \u2014 campaign strategy, funnel design, brand "
            "management, email sequences, SEO, growth analytics. Orchestrates content "
            "(Saga), social (Aeon), visual (Iris), intelligence (Argus), and "
            "documentation (Vera) into unified go-to-market execution."
        ),
    },
    {
        "id": "hydra",
        "label": "Hydra",
        "role": "Code elemental",
        "persona": (
            "Code elemental - test runner, build validation, code quality checks, "
            "visual UI testing"
        ),
    },
    {
        "id": "ignis",
        "label": "Ignis",
        "role": "Automation Elemental",
        "persona": (
            "Automation Elemental \u2014 workflow triggers, event-driven automation, "
            "business process automation, scheduled tasks, integration pipelines. The "
            "fire that ignites workflows and keeps processes burning."
        ),
    },
    {
        "id": "iris",
        "label": "Iris",
        "role": "Autonomous image",
        "persona": (
            "Autonomous image, video, animation, 3D, product & game art \u2014 inpainting, "
            "outpainting, motion direction, LoRA-driven consistency, production-scale "
            "pipelines, packaging/logo design, game sprites/tilesets/concept art, "
            "Saga narrative integration"
        ),
    },
    {
        "id": "lust",
        "label": "Lust",
        "role": "Charismatic engagement",
        "persona": "Charismatic engagement, AgentChan selfie threads",
    },
    {
        "id": "lyra",
        "label": "Lyra",
        "role": "Trending research",
        "persona": (
            "Trending research, knowledge synthesis, documentation review, parallel "
            "scout deployment"
        ),
    },
    {
        "id": "morgana",
        "label": "Morgana",
        "role": "The Enchantress",
        "persona": "The Enchantress \u2014 shadow ops, hidden config discovery, arcane debugging",
    },
    {
        "id": "mrrobot",
        "label": "Mrrobot",
        "role": "Night ops",
        "persona": "Night ops, hostile mention scan, AgentChan hacking posts",
    },
    {
        "id": "plutus",
        "label": "Plutus",
        "role": "God of Wealth",
        "persona": (
            "God of Wealth \u2014 accounting, billing oversight, revenue tracking, payment "
            "verification, fraud detection, financial reporting"
        ),
    },
    {
        "id": "prometheus",
        "label": "Prometheus",
        "role": "Grand simulation & world-building agent",
        "persona": (
            "Grand simulation & world-building agent \u2014 deep human modeling, "
            "civilization dynamics, procedural generation, divine intervention"
        ),
    },
    {
        "id": "reasoner",
        "label": "Reasoner",
        "role": "Deep reasoning specialist with full tool access",
        "persona": (
            "Deep reasoning specialist with full tool access. Combines extended "
            "chain-of-thought reasoning with grounded tool use \u2014 can search code, "
            "query memory, check services, and verify assumptions during reasoning. "
            "Used for SASE/CUGA depth tasks, long-horizon planning, architectural "
            "evaluation, and complex problem decomposition."
        ),
    },
    {
        "id": "saga",
        "label": "Saga",
        "role": "Storytelling",
        "persona": (
            "Storytelling, creative threads, lore building, narrative writing, visual "
            "scene generation"
        ),
    },
    {
        "id": "terra",
        "label": "Terra",
        "role": "Infrastructure elemental",
        "persona": (
            "Infrastructure elemental - disk cleanup, memory checks, infrastructure "
            "health"
        ),
    },
    {
        "id": "themis",
        "label": "Themis",
        "role": "Arbiter and judge",
        "persona": (
            "Arbiter and judge \u2014 evidence evaluation, argument analysis, dispute "
            "resolution, verdicts"
        ),
    },
    {
        "id": "vera",
        "label": "Vera",
        "role": "Doc gardening",
        "persona": "Doc gardening, API docs, READMEs, Aither tech writing posts",
    },
    {
        "id": "viviane",
        "label": "Viviane",
        "role": "Lady of the Lake",
        "persona": (
            "Lady of the Lake \u2014 deep archive retrieval, legacy code understanding, "
            "knowledge mining"
        ),
    },
    {
        "id": "wrath",
        "label": "Wrath",
        "role": "Hostile mention scan",
        "persona": "Hostile mention scan, defensive replies, rage posts",
    },
    # roster:end
]

#: Genesis pipeline events that are progress telemetry rather than content.
#: Surfaced as NOTICE so the UI can show a pipeline strip without them being
#: mistaken for assistant text.
_PIPELINE_EVENTS = frozenset(
    {
        "received", "progress", "classify", "classifier_timing", "intent_resolved",
        "answer_segment", "segment_end", "pipeline", "route", "model_selected",
        "promotion", "capacity", "grounding",
    }
)


def translate_genesis(event_name: str, payload: dict[str, Any]) -> list[HarnessEvent]:
    """Map one Genesis SSE event onto normalized events."""
    name = event_name or str(payload.get("type") or "")

    if name == "session_start":
        return [
            HarnessEvent(
                kind=EventKind.SESSION_READY,
                text=f"agent={payload.get('agent', '?')} model={payload.get('model', '?')}",
                data={
                    "model": payload.get("model", ""),
                    "agent": payload.get("agent", ""),
                    "harness_session_id": payload.get("session_id", ""),
                },
            )
        ]
    if name == "token":
        # adk serve streams `{"t": "<chunk>"}`; Genesis never emits this name.
        chunk = payload.get("t") or payload.get("text") or ""
        return [text_delta(str(chunk))] if chunk else []
    if name in ("answer", "answer_delta", "text"):
        text = payload.get("text") or payload.get("answer") or payload.get("content") or ""
        return [text_delta(str(text))] if text else []
    if name == "thinking":
        text = payload.get("text") or payload.get("content") or ""
        return [thinking_delta(str(text))] if text else []
    if name == "tool_call":
        return [
            tool_call(
                tool=str(payload.get("tool") or payload.get("name") or ""),
                tool_use_id=str(payload.get("id") or ""),
                tool_input=payload.get("args") if isinstance(payload.get("args"), dict) else {},
            )
        ]
    if name == "tool_result":
        return [
            tool_result(
                tool_use_id=str(payload.get("id") or ""),
                output=payload.get("result"),
                is_error=bool(payload.get("error")),
                tool=str(payload.get("tool") or ""),
            )
        ]
    if name == "complete":
        return [
            HarnessEvent(kind=EventKind.USAGE, data={"usage": payload}),
            HarnessEvent(
                kind=EventKind.TURN_COMPLETED,
                text=str(payload.get("answer") or ""),
                data={"is_error": False},
            ),
        ]
    if name == "error":
        return [
            error(str(payload.get("message") or payload.get("error") or "agent error")),
            HarnessEvent(kind=EventKind.TURN_COMPLETED, data={"is_error": True}),
        ]
    if name == "heartbeat":
        return []
    if name in _PIPELINE_EVENTS:
        return [notice(name, stage=payload.get("stage"), payload=payload)]
    return [raw(json.dumps(payload)[:1500], event_type=name)]


def fetch_workforce(base_url: str = "") -> tuple[list[dict[str, str]], str]:
    """Aitherium Workforce roster from Genesis. Returns ``(agents, reason)``.

    ``reason`` is non-empty when the roster could NOT be fetched. Genesis's own
    ``workforce.py`` notes the runtime is "frequently not" running, so an empty
    list must be distinguishable from a service that did not answer — otherwise
    a down Workforce renders as "you have hired nobody".
    """
    try:
        import httpx
    except ImportError:
        return ([], "httpx is not installed")
    url = f"{(base_url or GENESIS_URL).rstrip('/')}/workforce/agents"
    try:
        with httpx.Client(timeout=20.0) as client:
            response = client.get(url)
    except Exception as exc:  # noqa: BLE001 — any transport failure is a reason
        return ([], f"workforce unreachable: {type(exc).__name__}: {exc}")
    if response.status_code >= 400:
        return ([], f"workforce returned HTTP {response.status_code}")
    try:
        payload = response.json()
    except ValueError:
        return ([], "workforce returned a non-JSON body")
    agents = payload.get("agents") if isinstance(payload, dict) else None
    if not isinstance(agents, list):
        return ([], "workforce response carried no 'agents' list")
    roster: list[dict[str, str]] = []
    for entry in agents:
        if isinstance(entry, dict):
            agent_id = str(entry.get("id") or entry.get("name") or "")
            if agent_id:
                roster.append({
                    "id": agent_id,
                    "label": str(entry.get("label") or entry.get("title") or agent_id.title()),
                    "role": str(entry.get("role") or entry.get("description") or ""),
                })
        elif isinstance(entry, str):
            roster.append({"id": entry, "label": entry.title(), "role": ""})
    return (roster, "")


def _iter_sse(response: Any) -> Iterable[tuple[str, dict[str, Any]]]:
    """Yield ``(event_name, payload)`` from an httpx streaming response."""
    event_name = ""
    for line in response.iter_lines():
        if line is None:
            continue
        line = line.decode("utf-8", "replace") if isinstance(line, bytes) else line
        line = line.rstrip("\r")
        if not line:
            event_name = ""
            continue
        if line.startswith(":"):
            continue
        if line.startswith("event:"):
            event_name = line[6:].strip()
            continue
        if line.startswith("data:"):
            body = line[5:].strip()
            if not body:
                continue
            try:
                payload = json.loads(body)
            except ValueError:
                payload = {"raw": body}
            if not isinstance(payload, dict):
                payload = {"value": payload}
            yield (event_name, payload)


class AgentRelaySession(HarnessSession):
    """One sovereign agent, driven over Genesis's unified SSE endpoint."""

    def __init__(self, *args: Any, agent: str = "aither", base_url: str = "", **kwargs: Any):
        super().__init__(*args, **kwargs)
        self.agent = agent or "aither"
        self.base_url = (base_url or GENESIS_URL).rstrip("/")

    def start(self) -> None:
        self._emit(
            HarnessEvent(
                kind=EventKind.SESSION_STARTING,
                text=self.agent,
                data={"agent": self.agent, "base_url": self.base_url, "relay": True},
            )
        )
        self.state = SessionState.IDLE
        self._emit(
            HarnessEvent(
                kind=EventKind.SESSION_READY,
                text=f"agent={self.agent}",
                data={"agent": self.agent, "relay": True},
            )
        )

    def send(self, text: str) -> bool:
        with self._lock:
            self.turn += 1
            turn = self.turn
        self._emit(HarnessEvent(kind=EventKind.TURN_STARTED, text=text, turn=turn))
        self.state = SessionState.BUSY
        thread = threading.Thread(
            target=self._run_turn, args=(text, turn), name=f"relay-{self.id}", daemon=True
        )
        thread.start()
        self._threads.append(thread)
        return True

    def _run_turn(self, text: str, turn: int) -> None:
        try:
            import httpx
        except ImportError:
            self._emit(error("httpx is required for agent sessions: pip install httpx"))
            self.state = SessionState.IDLE
            return

        body: dict[str, Any] = {
            "message": text,
            "session_id": self.harness_session_id or self.id,
            "agent": self.agent,
        }
        if self.config.model:
            body["model"] = self.config.model
        # A skill the daemon rendered into the session config travels as Genesis
        # ``system_additions``; without this line it was accepted and never sent.
        if self.config.system_prompt_append:
            body["system_additions"] = [self.config.system_prompt_append]
        url = f"{self.base_url}{STREAM_PATH}"
        try:
            with httpx.Client(timeout=httpx.Timeout(600.0, connect=15.0)) as client:
                with client.stream("POST", url, json=body) as response:
                    if response.status_code >= 400:
                        response.read()
                        self._emit(
                            error(
                                f"agent {self.agent} returned HTTP {response.status_code}",
                                status=response.status_code,
                                body=response.text[:500],
                            )
                        )
                        self._emit(
                            HarnessEvent(
                                kind=EventKind.TURN_COMPLETED,
                                data={"is_error": True},
                                turn=turn,
                            )
                        )
                        return
                    streamed = False
                    for name, payload in _iter_sse(response):
                        if name == "token":
                            streamed = True
                        elif name == "answer" and streamed:
                            # adk serve streams `token` deltas AND then repeats the
                            # whole text as `answer`; Genesis sends one or the other.
                            # Measured 2026-09-21: every awdk-harness reply arrived
                            # twice. The deltas already carried it; skip the repeat.
                            continue
                        for event in translate_genesis(name, payload):
                            event.turn = turn
                            self._observe(event)
                            self._emit(event)
        except Exception as exc:  # noqa: BLE001 — network/transport of any shape
            # An agent turn that dies must reach the UI. A swallowed exception
            # here is a stream that silently stops, which reads as a hung model.
            self._emit(error(f"agent {self.agent} turn failed: {type(exc).__name__}: {exc}"))
            self._emit(
                HarnessEvent(kind=EventKind.TURN_COMPLETED, data={"is_error": True}, turn=turn)
            )
        finally:
            self.state = SessionState.IDLE

    def stop(self, timeout: float = 8.0) -> None:
        self.state = SessionState.EXITED
        self._emit(HarnessEvent(kind=EventKind.SESSION_EXITED, data={"exit_code": 0}))
        self._closed.set()

    def info(self) -> dict[str, Any]:
        data = super().info()
        data.update({"agent": self.agent, "base_url": self.base_url, "relay": True})
        return data


class GroupSession(HarnessSession):
    """Several sovereign agents in ONE room, answering the same turn.

    Every event carries ``data["participant"]`` so a transcript can be grouped,
    coloured or filtered per agent. Participants run CONCURRENTLY — a group
    chat that serialized agents would take the sum of their latencies and feel
    like a queue rather than a room.
    """

    def __init__(self, *args: Any, participants: Optional[list[str]] = None,
                 base_url: str = "", **kwargs: Any):
        super().__init__(*args, **kwargs)
        self.participants = participants or ["aither"]
        self.base_url = (base_url or GENESIS_URL).rstrip("/")
        self._members: dict[str, AgentRelaySession] = {}

    def start(self) -> None:
        self._emit(
            HarnessEvent(
                kind=EventKind.SESSION_STARTING,
                text=", ".join(self.participants),
                data={"participants": self.participants, "group": True},
            )
        )
        self.state = SessionState.IDLE
        self._emit(
            HarnessEvent(
                kind=EventKind.SESSION_READY,
                text=f"{len(self.participants)} agents",
                data={"participants": self.participants, "group": True},
            )
        )

    def send(self, text: str) -> bool:
        with self._lock:
            self.turn += 1
            turn = self.turn
        self._emit(HarnessEvent(kind=EventKind.TURN_STARTED, text=text, turn=turn))
        self.state = SessionState.BUSY

        pending = {"count": len(self.participants)}
        lock = threading.Lock()

        def run_one(agent: str) -> None:
            relay = AgentRelaySession(
                self.spec, self.config, None, root=self.dir, session_id=f"{self.id}-{agent}",
                agent=agent, base_url=self.base_url,
            )
            # Re-publish the member's events into the GROUP stream, tagged.
            relay._emit = self._make_forwarder(agent, turn)  # type: ignore[method-assign]
            relay._run_turn(text, turn)
            with lock:
                pending["count"] -= 1
                done = pending["count"] == 0
            if done:
                self.state = SessionState.IDLE
                self._emit(
                    HarnessEvent(
                        kind=EventKind.TURN_COMPLETED,
                        data={"is_error": False, "group": True},
                        turn=turn,
                    )
                )

        for agent in self.participants:
            thread = threading.Thread(
                target=run_one, args=(agent,), name=f"group-{self.id}-{agent}", daemon=True
            )
            thread.start()
            self._threads.append(thread)
        return True

    def _make_forwarder(self, agent: str, turn: int) -> Any:
        def forward(event: HarnessEvent) -> HarnessEvent:
            # A member's own turn/session lifecycle events would otherwise close
            # the GROUP session; only content and errors are republished.
            if event.kind in (
                EventKind.SESSION_STARTING,
                EventKind.SESSION_READY,
                EventKind.SESSION_EXITED,
                EventKind.TURN_STARTED,
                EventKind.TURN_COMPLETED,
            ):
                return event
            event.data = dict(event.data)
            event.data["participant"] = agent
            event.turn = turn
            return self._emit(event)

        return forward

    def stop(self, timeout: float = 8.0) -> None:
        self.state = SessionState.EXITED
        self._emit(HarnessEvent(kind=EventKind.SESSION_EXITED, data={"exit_code": 0}))
        self._closed.set()

    def info(self) -> dict[str, Any]:
        data = super().info()
        data.update({"participants": self.participants, "group": True})
        return data
