#!/usr/bin/env python3
"""Vendor skills into the awdk Claude Code plugin (``adk/harnesses/claude_mod/skills``).

Sources, both in the monorepo that holds ``awdk/``:

* ``awskills/skills/<name>.md``      -> ``skills/<name>/SKILL.md``
* ``.claude/skills/<brick>/**``      -> ``skills/<brick>/**`` for every ``<brick>`` that is a
  brick package in the monorepo (a brick's own skill wins over an awskills one)

The plugin's ``skills/`` directory is OWNED by this script: it is rebuilt from the
sources, stale entries are removed, text is normalised to LF. Running it twice changes
nothing. ``EXCLUDE`` names skills that are personal aliases, not product skills.

    python awdk/scripts/sync_claude_mod.py            # write
    python awdk/scripts/sync_claude_mod.py --check    # exit 1 when the vendored copy drifted
    python awdk/scripts/sync_claude_mod.py --root DIR # a different monorepo root

Exit: 0 in sync / written, 1 drift (--check), 2 cannot run (sources missing).
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

AWDK = Path(__file__).resolve().parent.parent
DEFAULT_ROOT = AWDK.parent
PLUGIN_REL = Path("awdk/adk/harnesses/claude_mod")
README = "README.md"
EXCLUDE = frozenset({"code-like-david"})
#: A skill naming an internal monorepo tree is not public: it is skipped whole (and
#: listed), never half-copied. tools/publish_gate.py --deny-internal is the backstop.
INTERNAL = re.compile(rb"(?<![\w/])\.(?:DEPLOYMENT|AITHERIUM|PRODUCTS)/")
#: Internal ledger/checker ids and the monorepo path are what the wheel boundary gate
#: (check_adk_publishable.py ADK001, PATTERNS, in the private tree) refuses in a shipped
#: file, and the vendored tree ships inside adk. Kept in step with that list by hand: a
#: skill carrying one is skipped whole, exactly like INTERNAL above.
INTERNAL_IDS = re.compile(
    rb"\bD-\d{3,5}\b"
    rb"|\b(?:NX|SEC|PQ|HYG|QS|EMC|ST|AWG|NAV|CSR|ACG|MCP|BW|ONB|AC|WT)\d{3}[A-Z]?\b"
    rb"|[A-Za-z]:[\\/]AitherOS-Fresh"
)


def _internal(data: bytes) -> bool:
    """True when a skill must not ship: an internal tree, ledger/checker id or path."""
    return bool(INTERNAL.search(data) or INTERNAL_IDS.search(data))


README_TEXT = (
    "# Vendored skills\n\n"
    "Generated by `awdk/scripts/sync_claude_mod.py` from `awskills/skills/` and the brick\n"
    "skills in `.claude/skills/`. Do not edit here; edit the source and re-run it.\n"
)


def _text(p: Path) -> bytes:
    return p.read_bytes().replace(b"\r\n", b"\n")


def expected(root: Path, skipped: list[str] | None = None) -> dict[str, bytes]:
    """Relative path under ``skills/`` -> content, for the whole vendored tree."""
    out: dict[str, bytes] = {README: README_TEXT.encode()}
    skipped = [] if skipped is None else skipped
    aws = root / "awskills" / "skills"
    for md in sorted(aws.glob("*.md")) if aws.is_dir() else []:
        if md.stem in EXCLUDE:
            continue
        data = _text(md)
        if _internal(data):
            skipped.append(md.stem)
            continue
        out[f"{md.stem}/SKILL.md"] = data
    packages = root / "AitherOS" / "packages"
    cskills = root / ".claude" / "skills"
    for sdir in sorted(cskills.iterdir()) if cskills.is_dir() else []:
        name = sdir.name
        if name in EXCLUDE or not (packages / name).is_dir():
            continue
        if not (sdir / "SKILL.md").is_file():
            continue
        files = {f"{name}/{f.relative_to(sdir).as_posix()}": _text(f)
                 for f in sorted(sdir.rglob("*"))
                 if f.is_file() and "__pycache__" not in f.parts}
        if any(_internal(v) for v in files.values()):
            skipped.append(name)
            continue
        for k in [k for k in out if k.startswith(f"{name}/")]:
            del out[k]
        out.update(files)
    return out


def actual(dest: Path) -> dict[str, bytes]:
    if not dest.is_dir():
        return {}
    return {f.relative_to(dest).as_posix(): f.read_bytes()
            for f in sorted(dest.rglob("*")) if f.is_file()}


def write(dest: Path, want: dict[str, bytes]) -> int:
    have = actual(dest)
    changed = 0
    for rel in sorted(set(have) - set(want)):
        (dest / rel).unlink()
        changed += 1
    for rel, data in want.items():
        if have.get(rel) != data:
            target = dest / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            changed += 1
    for d in sorted((p for p in dest.rglob("*") if p.is_dir()), reverse=True):
        if not any(d.iterdir()):
            shutil.rmtree(d)
    return changed


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    root = a.root.resolve()
    if not (root / "awskills" / "skills").is_dir() or not (root / ".claude" / "skills").is_dir():
        print(f"sync_claude_mod: sources missing under {root} (need awskills/skills and "
              ".claude/skills); cannot judge", file=sys.stderr)
        return 2
    dest = root / PLUGIN_REL / "skills"
    skipped: list[str] = []
    want = expected(root, skipped)
    if skipped:
        print(f"sync_claude_mod: skipped (names an internal tree): {', '.join(skipped)}")
    if a.check:
        have = actual(dest)
        drift = sorted(k for k in set(want) | set(have) if want.get(k) != have.get(k))
        for rel in drift[:20]:
            print(f"drift: skills/{rel}")
        print(f"sync_claude_mod: {len(want)} files, {len(drift)} drifted")
        return 1 if drift else 0
    n = write(dest, want)
    print(f"sync_claude_mod: {len(want)} files, {n} written/removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
