#!/usr/bin/env python3
"""Vendor skills into the awdk Claude Code plugin (``adk/harnesses/claude_mod/skills``).

Sources, both in the monorepo that holds ``awdk/``:

* ``awskills/skills/<name>.md``      -> ``skills/<name>/SKILL.md``
* ``.claude/skills/<brick>/**``      -> ``skills/<brick>/**`` for every ``<brick>`` that is a
  brick package in the monorepo (a brick's own skill wins over an awskills one)

The plugin's ``skills/`` directory is OWNED by this script: it is rebuilt from the
sources, stale entries are removed, text is normalised to LF. Running it twice changes
nothing. ``EXCLUDE`` names skills that are personal aliases, not product skills.

awskills is the ONE source of the public skills. Every awskills-derived ``SKILL.md``
carries a "generated, edit the pack" marker right after its frontmatter, and a skill the
public pack itself holds back (``SYNC_EXCLUDES`` in ``.github/workflows/sync-skills.yml``,
read from that file so the two lists cannot disagree) is never vendored either: awdk is
public, so it must not ship what the public pack refuses to.

Measured 2026-10-05: 58 of the 107 vendored skills had drifted from their sources (the
2026-10-04 awskills audit fixes never reached awdk) and ``character-art-studio`` and
``llm-serving`` shipped in awdk while the pack excluded them -- the generator existed but
nothing ran it, and ``--check`` compared raw bytes, so on a CRLF checkout it reported
every file as drifted and read as noise.

    python awdk/scripts/sync_claude_mod.py            # write
    python awdk/scripts/sync_claude_mod.py --check    # exit 1 when the vendored copy drifted
    python awdk/scripts/sync_claude_mod.py --self-test  # prove --check can still fail
    python awdk/scripts/sync_claude_mod.py --root DIR # a different monorepo root

Exit: 0 in sync / written, 1 drift (--check) or a failed self-test, 2 cannot run
(sources missing, or the public exclude list cannot be read).
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
from pathlib import Path

AWDK = Path(__file__).resolve().parent.parent
DEFAULT_ROOT = AWDK.parent
PLUGIN_REL = Path("awdk/adk/harnesses/claude_mod")
README = "README.md"
EXCLUDE = frozenset({"code-like-david"})
#: A skill naming an internal monorepo tree is not public: it is skipped whole (and
#: listed), never half-copied. tools/publish_gate.py --deny-internal is the backstop.
INTERNAL = re.compile(rb"(?<![\w/])\.(?:DEPLOYMENT|AITHERIUM|PRODUCTS)/")
#: Internal ledger/checker ids and the monorepo path are what the wheel boundary gate
#: (check_adk_publishable.py ADK001, PATTERNS, in the private tree) refuses in a shipped
#: file, and the vendored tree ships inside adk. Kept in step with that list by hand: a
#: skill carrying one is skipped whole, exactly like INTERNAL above.
INTERNAL_IDS = re.compile(
    rb"\bD-\d{3,5}\b"
    rb"|\b(?:NX|SEC|PQ|HYG|QS|EMC|ST|AWG|NAV|CSR|ACG|MCP|BW|ONB|AC|WT)\d{3}[A-Z]?\b"
    rb"|[A-Za-z]:[\\/]AitherOS-Fresh"
)


def _internal(data: bytes) -> bool:
    """True when a skill must not ship: an internal tree, ledger/checker id or path."""
    return bool(INTERNAL.search(data) or INTERNAL_IDS.search(data))


README_TEXT = (
    "# Vendored skills\n\n"
    "Generated by `awdk/scripts/sync_claude_mod.py` from `awskills/skills/` and the brick\n"
    "skills in `.claude/skills/`. Do not edit here; edit the source and re-run it.\n"
    "The awskills pack (github.com/Aitherium/awskills) is the single source of every\n"
    "skill here that is not an aw* brick's own skill; a skill the pack keeps out of its\n"
    "public mirror is kept out of awdk too.\n"
)

#: The workflow that publishes the awskills pack, and the variable naming the skills it
#: holds back from the public mirror (``--exclude=<name>.md`` flags).
SYNC_SKILLS_WF = Path(".github/workflows/sync-skills.yml")
SYNC_EXCLUDES_RE = re.compile(r'^\s*SYNC_EXCLUDES:\s*"([^"]*)"', re.MULTILINE)


class CannotRunError(Exception):
    """A source the generator must read is absent or unreadable (exit 2)."""


def public_excludes(root: Path) -> frozenset[str]:
    """Skill names the public awskills mirror refuses, read from sync-skills.yml.

    Absent workflow (a fixture tree, the public mirror) -> nothing excluded beyond
    ``EXCLUDE``. Present but without a parseable SYNC_EXCLUDES -> CannotRunError: a renamed
    variable must not silently start shipping the internal-only skills.
    """
    wf = root / SYNC_SKILLS_WF
    if not wf.is_file():
        return frozenset()
    m = SYNC_EXCLUDES_RE.search(wf.read_text(encoding="utf-8", errors="replace"))
    if not m:
        raise CannotRunError(f"{SYNC_SKILLS_WF} has no SYNC_EXCLUDES line")
    names = re.findall(r"--exclude=([\w.-]+?)\.md\b", m.group(1))
    if m.group(1).strip() and not names:
        raise CannotRunError(f"{SYNC_SKILLS_WF} SYNC_EXCLUDES is not --exclude=<name>.md flags")
    return frozenset(names)


def marker(name: str) -> bytes:
    return (f"<!-- Generated from the awskills pack (skills/{name}.md, "
            "github.com/Aitherium/awskills). Edit the pack, never this copy. -->\n").encode()


def stamp(name: str, data: bytes) -> bytes:
    """Insert the generated-from marker right after the YAML frontmatter (or at top)."""
    if data.startswith(b"---\n"):
        end = data.find(b"\n---\n", 3)
        if end != -1:
            cut = end + len(b"\n---\n")
            return data[:cut] + marker(name) + data[cut:]
    return marker(name) + data


def _text(p: Path) -> bytes:
    return p.read_bytes().replace(b"\r\n", b"\n")


def expected(root: Path, skipped: list[str] | None = None) -> dict[str, bytes]:
    """Relative path under ``skills/`` -> content, for the whole vendored tree."""
    out: dict[str, bytes] = {README: README_TEXT.encode()}
    skipped = [] if skipped is None else skipped
    excluded = EXCLUDE | public_excludes(root)
    aws = root / "awskills" / "skills"
    for md in sorted(aws.glob("*.md")) if aws.is_dir() else []:
        if md.stem in excluded:
            continue
        data = _text(md)
        if _internal(data):
            skipped.append(md.stem)
            continue
        out[f"{md.stem}/SKILL.md"] = stamp(md.stem, data)
    packages = root / "AitherOS" / "packages"
    cskills = root / ".claude" / "skills"
    for sdir in sorted(cskills.iterdir()) if cskills.is_dir() else []:
        name = sdir.name
        if name in EXCLUDE or not (packages / name).is_dir():
            continue
        if not (sdir / "SKILL.md").is_file():
            continue
        files = {f"{name}/{f.relative_to(sdir).as_posix()}": _text(f)
                 for f in sorted(sdir.rglob("*"))
                 if f.is_file() and "__pycache__" not in f.parts}
        if any(_internal(v) for v in files.values()):
            skipped.append(name)
            continue
        for k in [k for k in out if k.startswith(f"{name}/")]:
            del out[k]
        out.update(files)
    return out


def actual(dest: Path) -> dict[str, bytes]:
    if not dest.is_dir():
        return {}
    return {f.relative_to(dest).as_posix(): f.read_bytes()
            for f in sorted(dest.rglob("*")) if f.is_file()}


def write(dest: Path, want: dict[str, bytes]) -> int:
    have = actual(dest)
    changed = 0
    for rel in sorted(set(have) - set(want)):
        (dest / rel).unlink()
        changed += 1
    for rel, data in want.items():
        # LF-equal counts as current: a CRLF checkout of an in-sync file is not rewritten.
        if rel not in have or have[rel].replace(b"\r\n", b"\n") != data:
            target = dest / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            changed += 1
    for d in sorted((p for p in dest.rglob("*") if p.is_dir()), reverse=True):
        if not any(d.iterdir()):
            shutil.rmtree(d)
    return changed


def self_test() -> int:
    """Prove --check can still fail: each arm builds a fixture tree and asserts a verdict."""
    failures: list[str] = []

    def arm(name: str, ok: bool) -> None:
        print(f"  {'ok  ' if ok else 'FAIL'} {name}")
        if not ok:
            failures.append(name)

    wf_text = ('env:\n  SYNC_EXCLUDES: "--exclude=held.md"\n')
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        aws = root / "awskills" / "skills"
        aws.mkdir(parents=True)
        (aws / "alpha.md").write_bytes(b"---\nname: alpha\n---\r\nbody\r\n")
        (aws / "held.md").write_text("---\nname: held\n---\ninternal-only\n")
        (root / ".claude" / "skills").mkdir(parents=True)
        (root / SYNC_SKILLS_WF).parent.mkdir(parents=True)
        (root / SYNC_SKILLS_WF).write_text(wf_text)
        dest = root / PLUGIN_REL / "skills"
        quiet = ["--root", str(root)]
        arm("empty vendored tree is drift (exit 1)", main(quiet + ["--check"]) == 1)
        arm("write exits 0", main(quiet) == 0)
        arm("fresh write checks clean (exit 0)", main(quiet + ["--check"]) == 0)
        body = (dest / "alpha" / "SKILL.md").read_bytes()
        arm("marker sits right after the frontmatter",
            body.startswith(b"---\nname: alpha\n---\n<!-- Generated from the awskills"))
        arm("a publicly excluded skill is not vendored", not (dest / "held").exists())
        (dest / "alpha" / "SKILL.md").write_bytes(body.replace(b"\n", b"\r\n"))
        arm("a CRLF checkout of an in-sync copy is not drift",
            main(quiet + ["--check"]) == 0)
        (dest / "alpha" / "SKILL.md").write_bytes(body + b"hand edit\n")
        arm("a hand edit is drift (exit 1)", main(quiet + ["--check"]) == 1)
        main(quiet)
        (dest / "held").mkdir()
        (dest / "held" / "SKILL.md").write_text("x\n")
        arm("a vendored excluded skill is drift (exit 1)", main(quiet + ["--check"]) == 1)
        (aws / "alpha.md").write_text("---\nname: alpha\n---\nsource changed\n")
        arm("a changed source is drift (exit 1)", main(quiet + ["--check"]) == 1)
        (root / SYNC_SKILLS_WF).write_text("env:\n  OTHER: 1\n")
        arm("unreadable SYNC_EXCLUDES cannot judge (exit 2)",
            main(quiet + ["--check"]) == 2)
    with tempfile.TemporaryDirectory() as tmp:
        arm("missing sources cannot judge (exit 2)",
            main(["--root", tmp, "--check"]) == 2)
    print(f"sync_claude_mod self-test: {'FAIL' if failures else 'ok'} "
          f"({len(failures)} failed)")
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return self_test()
    root = a.root.resolve()
    if not (root / "awskills" / "skills").is_dir() or not (root / ".claude" / "skills").is_dir():
        print(f"sync_claude_mod: sources missing under {root} (need awskills/skills and "
              ".claude/skills); cannot judge", file=sys.stderr)
        return 2
    dest = root / PLUGIN_REL / "skills"
    skipped: list[str] = []
    try:
        want = expected(root, skipped)
    except CannotRunError as exc:
        print(f"sync_claude_mod: {exc}; cannot judge", file=sys.stderr)
        return 2
    if skipped:
        print(f"sync_claude_mod: skipped (names an internal tree): {', '.join(skipped)}")
    if a.check:
        # Compare as text with LF line ends: a Windows checkout (core.autocrlf) holds
        # the committed LF blobs as CRLF, and byte equality reported every file drifted.
        have = {k: v.replace(b"\r\n", b"\n") for k, v in actual(dest).items()}
        drift = sorted(k for k in set(want) | set(have) if want.get(k) != have.get(k))
        for rel in drift[:20]:
            print(f"drift: skills/{rel}")
        print(f"sync_claude_mod: {len(want)} files, {len(drift)} drifted")
        return 1 if drift else 0
    n = write(dest, want)
    print(f"sync_claude_mod: {len(want)} files, {n} written/removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
