# vendored from aither-kaggle-agent@a5cd9b6532eb039dd5b7c27633293dfd55672a9c:agent/synth/generate.py -- import paths; suite_seed may be a str ('%d' -> '%s', identical for ints) (see _provenance.py)
"""Seeded, parameterised level and game generators for the h25 synthetic suite.

Five families, each a multi-level game whose mechanic persists across levels
while the board, the piece count and the optimal solution length grow:

  push     push-box-to-target (Sokoban), 1-3 boxes; generated by random PULLS
           from the solved state, so every level is solvable by construction
  lights   lights-out: a click toggles a cell and its 4 neighbours; clear the board
  keydoor  maze with coloured keys and matching doors (1-2), lava = GAME_OVER
  recolor  click a canvas cell to cycle its colour; match the pattern on the right
  tilt     gravity / sliding tiles: every tile slides until blocked; rest the
           player tile on the goal (1-3 tiles)

Every level's optimal length is computed by ``solve.bfs`` over the same rules
the game file embeds. ``baseline_actions`` (the RHAE human baseline) is
``ceil(HUMAN_FACTOR * optimal)`` with ``HUMAN_FACTOR = 1.5``: the measured
public games put humans well above optimal, and 1.5x keeps a level beaten at the
optimum capped (1.5^2 = 2.25 > 1.15) while a 2x-optimal agent still scores
(0.75^2 = 0.56). ``optimal_actions`` is written next to it in metadata.json.

Half the games (seeded) carry a HUD move meter: two extra rows on top, a bar
that shrinks one step per counted action; running out is GAME_OVER. Its budget
is ``2 * optimal + 10`` per level, so it never binds an optimal solver.
"""
from __future__ import annotations

import math
import random
from collections import deque
from typing import Any, Dict, List, Optional, Tuple

from . import rules
from .solve import SearchLimit, optimal_length

FAMILIES = ("push", "lights", "keydoor", "recolor", "tilt")
LETTER = {"push": "p", "lights": "l", "keydoor": "k", "recolor": "c", "tilt": "t"}
HUMAN_FACTOR = 1.5
MAX_TRIES = 400

Cell = Tuple[int, int]


class GenerationFailed(RuntimeError):
    pass


def human_baseline(opt: int) -> int:
    return max(1, int(math.ceil(HUMAN_FACTOR * opt)))


def _border(w: int, h: int) -> List[Cell]:
    return [(x, y) for y in range(h) for x in range(w) if x in (0, w - 1) or y in (0, h - 1)]


def _solve(lv: Dict[str, Any], max_states: int = 300_000) -> Optional[int]:
    try:
        return optimal_length(lv, max_states)
    except SearchLimit:
        return None


# ----------------------------------------------------------------------------
# families
# ----------------------------------------------------------------------------
def gen_push(rng: random.Random, i: int) -> Tuple[Dict[str, Any], int]:
    n = 5 + i  # interior side
    w = h = n + 2
    nb = min(1 + i // 2, 3)
    lo = 4 + 2 * i
    for _ in range(MAX_TRIES):
        walls = set(_border(w, h))
        for y in range(1, h - 1):
            for x in range(1, w - 1):
                if rng.random() < 0.10:
                    walls.add((x, y))
        free = [(x, y) for y in range(1, h - 1) for x in range(1, w - 1) if (x, y) not in walls]
        if len(free) < nb + 4:
            continue
        rng.shuffle(free)
        targets = free[:nb]
        boxes = list(targets)
        player = free[nb]
        occupied = set(walls)
        # random walk with pulls from the solved state: always solvable
        for _ in range(30 + 12 * i):
            dx, dy = rules.SY_DIRS[rng.randint(1, 4)]
            nx, ny = player[0] + dx, player[1] + dy
            if (nx, ny) in occupied or (nx, ny) in boxes:
                continue
            behind = (player[0] - dx, player[1] - dy)
            if behind in boxes and rng.random() < 0.7:
                boxes[boxes.index(behind)] = player
            player = (nx, ny)
        lv = {"family": "push", "w": w, "h": h, "walls": sorted(walls), "targets": sorted(targets),
              "boxes": sorted(boxes), "player": list(player)}
        opt = _solve(lv)
        if opt is not None and opt >= lo:
            return lv, opt
    raise GenerationFailed("push level %d" % i)


def gen_lights(rng: random.Random, i: int) -> Tuple[Dict[str, Any], int]:
    w, h = [(3, 3), (3, 3), (4, 3), (4, 4), (4, 4)][min(i, 4)]
    lo = 2 + i // 2
    for _ in range(MAX_TRIES):
        k = 2 + i + rng.randint(0, 1)
        clicks = rng.sample([(x, y) for y in range(h) for x in range(w)], k)
        lv = {"family": "lights", "w": w, "h": h, "walls": [], "start": 0}
        P = rules.prep(lv)
        s = 0
        for c in clicks:
            s = rules.apply(P, s, 6, c)[0]
        lv["start"] = s
        opt = _solve(lv)
        if opt is not None and opt >= lo:
            return lv, opt
    raise GenerationFailed("lights level %d" % i)


def _maze(rng: random.Random, m: int) -> set:
    """Perfect maze on an m x m cell lattice -> wall set on the (2m+1)^2 grid."""
    n = 2 * m + 1
    walls = {(x, y) for y in range(n) for x in range(n)}
    start = (rng.randrange(m), rng.randrange(m))
    stack = [start]
    seen = {start}
    walls.discard((2 * start[0] + 1, 2 * start[1] + 1))
    while stack:
        cx, cy = stack[-1]
        nbrs = [(cx + dx, cy + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                if 0 <= cx + dx < m and 0 <= cy + dy < m and (cx + dx, cy + dy) not in seen]
        if not nbrs:
            stack.pop()
            continue
        nx, ny = rng.choice(nbrs)
        seen.add((nx, ny))
        walls.discard((2 * nx + 1, 2 * ny + 1))
        walls.discard((cx + nx + 1, cy + ny + 1))
        stack.append((nx, ny))
    return walls


def _reach(n: int, walls: set, blocked: set, src: Cell) -> Dict[Cell, Cell]:
    """BFS parents over free cells, avoiding ``blocked``."""
    par: Dict[Cell, Cell] = {src: src}
    q = deque([src])
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            c = (x + dx, y + dy)
            if 0 <= c[0] < n and 0 <= c[1] < n and c not in walls and c not in blocked and c not in par:
                par[c] = (x, y)
                q.append(c)
    return par


def _path(par: Dict[Cell, Cell], dst: Cell) -> List[Cell]:
    out = [dst]
    while par[out[-1]] != out[-1]:
        out.append(par[out[-1]])
    return out[::-1]


def gen_keydoor(rng: random.Random, i: int) -> Tuple[Dict[str, Any], int]:
    m = 3 + i
    n = 2 * m + 1
    nk = 1 if i < 2 else 2
    lo = 6 + 3 * i
    for _ in range(MAX_TRIES):
        walls = _maze(rng, m)
        interior = [(x, y) for y in range(1, n - 1) for x in range(1, n - 1) if (x, y) in walls
                    and ((x % 2) != (y % 2))]  # removable walls between two cells
        for c in rng.sample(interior, min(len(interior), i)):
            walls.discard(c)
        cells = [(x, y) for y in range(n) for x in range(n) if (x, y) not in walls]
        player = rng.choice(cells)
        par = _reach(n, walls, set(), player)
        goal = max(par, key=lambda c: (len(_path(par, c)), c))
        route = _path(par, goal)
        if len(route) < 3 + 3 * nk:
            continue
        doors: List[Cell] = []
        keys: List[Cell] = []
        seg = max(1, (len(route) - 2) // nk)
        for d in range(nk):
            opts = [c for c in route[1 + d * seg:1 + (d + 1) * seg] if c != goal]
            if not opts:
                break
            door = rng.choice(opts)
            # the key lies on this side of ITS door (earlier doors may be open)
            region = [c for c in _reach(n, walls, {door}, player)
                      if c not in (player, goal) and c not in keys and c not in doors and c != door]
            if not region:
                break
            doors.append(door)
            keys.append(rng.choice(region))
        if len(doors) != nk:
            continue
        # every door must matter: without keys the goal is out of reach
        if goal in _reach(n, walls, set(doors), player):
            continue
        special = {player, goal, *keys, *doors}
        pool = [c for c in cells if c not in special]
        lava = rng.sample(pool, min(len(pool), i + rng.randint(0, 1)))
        lv = {"family": "keydoor", "w": n, "h": n, "walls": sorted(walls), "player": list(player),
              "goal": list(goal), "keys": [list(k) for k in keys], "doors": [list(d) for d in doors],
              "lava": sorted(lava)}
        opt = _solve(lv)
        if opt is not None and opt >= lo:
            return lv, opt
    raise GenerationFailed("keydoor level %d" % i)


def gen_recolor(rng: random.Random, i: int) -> Tuple[Dict[str, Any], int]:
    cw, ch, k = [(2, 2, 2), (3, 2, 3), (3, 3, 3), (4, 3, 2), (4, 4, 2)][min(i, 4)]
    lo = 2 + i
    w, h = 2 * cw + 1, ch
    for _ in range(MAX_TRIES):
        canvas = [rng.randrange(k) for _ in range(cw * ch)]
        target = [rng.randrange(k) for _ in range(cw * ch)]
        lv = {"family": "recolor", "w": w, "h": h, "cw": cw, "ch": ch, "k": k,
              "walls": [(cw, y) for y in range(ch)], "canvas": canvas, "target": target}
        opt = _solve(lv)
        if opt is not None and opt >= lo:
            return lv, opt
    raise GenerationFailed("recolor level %d" % i)


def gen_tilt(rng: random.Random, i: int) -> Tuple[Dict[str, Any], int]:
    n = 6 + i
    w = h = n + 2
    nt = 1 + (i >= 2) + (i >= 4)
    lo = 3 + i
    for _ in range(MAX_TRIES):
        walls = set(_border(w, h))
        for y in range(1, h - 1):
            for x in range(1, w - 1):
                if rng.random() < 0.16:
                    walls.add((x, y))
        free = [(x, y) for y in range(1, h - 1) for x in range(1, w - 1) if (x, y) not in walls]
        if len(free) < nt + 2:
            continue
        pick = rng.sample(free, nt + 1)
        lv = {"family": "tilt", "w": w, "h": h, "walls": sorted(walls), "goal": list(pick[0]),
              "tiles": [list(c) for c in pick[1:]]}
        opt = _solve(lv)
        if opt is not None and lo <= opt <= 40:
            return lv, opt
    raise GenerationFailed("tilt level %d" % i)


GENERATORS = {"push": gen_push, "lights": gen_lights, "keydoor": gen_keydoor,
              "recolor": gen_recolor, "tilt": gen_tilt}


# ----------------------------------------------------------------------------
# games
# ----------------------------------------------------------------------------
def game_spec(index: int, suite_seed: Any = 0, family: Optional[str] = None) -> Dict[str, Any]:
    """The full, JSON-serialisable description of synthetic game ``index``.

    Depends only on ``(suite_seed, index, family)``: ``random.Random`` seeded
    with a str is stable across processes and PYTHONHASHSEED."""
    fam = family or FAMILIES[index % len(FAMILIES)]
    rng = random.Random("h25:%s:%d:%s" % (suite_seed, index, fam))
    n_levels = rng.choice((3, 4, 5))
    levels: List[Dict[str, Any]] = []
    opts: List[int] = []
    for i in range(n_levels):
        lv, opt = GENERATORS[fam](rng, i)
        # JSON-normalise (tuples -> lists) so the spec round-trips unchanged
        lv = {k: ([list(c) for c in v] if k in ("walls", "lava", "targets", "boxes", "tiles") else v)
              for k, v in lv.items()}
        levels.append(lv)
        opts.append(opt)
    colours = list(range(16))
    rng.shuffle(colours)
    roles = rules.SY_FAMILY_ROLES[fam]
    palette = [-1] * rules.N_ROLES
    for r, c in zip(roles, colours):
        palette[r] = c
    spare = colours[len(roles):]
    meter = [2 * o + 10 for o in opts] if rng.random() < 0.5 else None
    short = "%s%03d" % (LETTER[fam], index)
    return {
        "short_id": short,
        "family": fam,
        "suite_seed": suite_seed,
        "index": index,
        "levels": levels,
        "optimal_actions": opts,
        "baseline_actions": [human_baseline(o) for o in opts],
        "human_factor": HUMAN_FACTOR,
        "actions": [1, 2, 3, 4] if fam in rules.SY_MOVE_FAMILIES else [6],
        "colors": palette,
        "background": palette[rules.R_FLOOR],
        "letterbox": spare[0],
        "meter": meter,
        "meter_color": spare[1],
        "meter_empty": spare[2],
    }
