"""Harness choice: who runs the agent's loop.

* ``aither``   -- adk's own agent (``AitherAgent``): the persona files become its
                  system prompt, the chosen model its LLM. Nothing to install.
* ``claude``   -- Claude Code. Detected through ``adk.harnesses.registry``; the
                  persona is written as a ``CLAUDE.md`` for the agent's workspace.
* ``openclaw`` -- OpenClaw, repointed at the chosen model by ``adk.connect``'s
* ``hermes``      framework templates (the same Rail-1 CONNECT configs adk ships),
                  plus the persona as a system-prompt file.

``connect_harness`` only WRITES config under ``<home>/harness/``; it never
edits another program's settings in place -- the output says where to merge.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

from .config import HarnessConfig, HomeConfig, HomeError, compose_system_prompt, home_dir

HARNESSES: Dict[str, str] = {
    "aither": "adk's native agent loop (no install)",
    "claude": "Claude Code (needs the `claude` CLI)",
    "openclaw": "OpenClaw web-research agent, repointed at your model",
    "hermes": "Hermes architecture agent, repointed at your model",
}

_MERGE_HINT = {
    "openclaw": "merge into your OpenClaw config (provider + tools.mcp)",
    "hermes": "merge into ~/.hermes/cli-config.yaml (model + mcp_servers)",
}


def choose_harness(kind: str, mcp_url: str = "") -> HarnessConfig:
    if kind not in HARNESSES:
        raise HomeError(f"unknown harness {kind!r}; choose one of "
                        f"{', '.join(HARNESSES)}")
    return HarnessConfig(kind=kind, mcp_url=mcp_url)


def harness_status(kind: str) -> Dict[str, Any]:
    """Can this machine run the harness?"""
    if kind == "aither":
        return {"kind": kind, "available": True, "detail": "built in"}
    if kind == "claude":
        try:
            from adk.harnesses import registry

            path = registry.resolve_binary(registry.get("claude"))
        except Exception as exc:  # noqa: BLE001 -- report, never crash status
            return {"kind": kind, "available": False, "detail": f"probe failed: {exc}"}
        return {"kind": kind, "available": bool(path),
                "detail": path or "install: npm i -g @anthropic-ai/claude-code"}
    if kind in ("openclaw", "hermes"):
        pack = Path(__file__).resolve().parents[1] / "packs" / kind / "agent.yaml"
        tmpl = (Path(__file__).resolve().parents[1] / "connect" / "templates"
                / f"{kind}.yaml.tmpl")
        ok = pack.is_file() and tmpl.is_file()
        return {"kind": kind, "available": ok,
                "detail": "brain pack + connect template present" if ok else
                f"missing {pack if not pack.is_file() else tmpl}"}
    raise HomeError(f"unknown harness {kind!r}")


def _model_endpoint(cfg: HomeConfig) -> str:
    if cfg.model.base_url:
        return cfg.model.base_url
    if cfg.model.provider == "anthropic":
        return "https://api.anthropic.com/v1"
    return "http://127.0.0.1:8080/v1"


def connect_harness(cfg: HomeConfig, root: Optional[Path] = None) -> Dict[str, Any]:
    """Write the harness's config into ``<home>/harness`` and say what to do next."""
    base = root or home_dir()
    out_dir = base / "harness"
    out_dir.mkdir(parents=True, exist_ok=True)
    prompt = compose_system_prompt(base)
    kind = cfg.harness.kind
    written: Dict[str, str] = {}

    if kind == "aither":
        return {"kind": kind, "written": written,
                "next": "run `adk home chat` or `adk home join <game-url>`"}

    if kind == "claude":
        p = out_dir / "CLAUDE.md"
        p.write_text(f"<!-- generated by `adk home harness claude` from "
                     f"{base / 'persona'} -- edit the persona files, not this -->\n\n"
                     + prompt + "\n", encoding="utf-8")
        written["CLAUDE.md"] = str(p)
        return {"kind": kind, "written": written, "status": harness_status(kind),
                "next": f"start Claude Code in {out_dir} (it reads CLAUDE.md there)"}

    if kind in ("openclaw", "hermes"):
        from adk.connect import render_connect

        # The key itself never lands in a file: the rendered config names the
        # env var, which both frameworks expand at load time.
        key_ref = "${" + (cfg.model.api_key_env or "AITHER_API_KEY") + "}"
        text = render_connect(kind, gateway_url=_model_endpoint(cfg),
                              mcp_url=cfg.harness.mcp_url or "http://127.0.0.1:8182/mcp",
                              api_key=key_ref)
        if cfg.model.model:
            text = text.replace("model: aitheros-default", f"model: {cfg.model.model}")
            text = text.replace('default: "aither-orchestrator"',
                                f'default: "{cfg.model.model}"')
        cfg_path = out_dir / f"{kind}.yaml"
        cfg_path.write_text(text, encoding="utf-8")
        prompt_path = out_dir / f"{kind}-system-prompt.md"
        prompt_path.write_text(prompt + "\n", encoding="utf-8")
        written[f"{kind}.yaml"] = str(cfg_path)
        written["system_prompt"] = str(prompt_path)
        return {"kind": kind, "written": written, "status": harness_status(kind),
                "next": f"{_MERGE_HINT[kind]}; use {prompt_path.name} as its "
                        "system prompt"}

    raise HomeError(f"unknown harness {kind!r}")


def build_native_agent(cfg: HomeConfig, root: Optional[Path] = None,
                       llm: Any = None, memory: Any = None) -> Any:
    """An ``AitherAgent`` wearing this home's persona and model."""
    from adk.agent import AitherAgent

    from .models import build_llm

    return AitherAgent(
        name=cfg.name,
        llm=llm if llm is not None else build_llm(cfg.model),
        memory=memory,
        system_prompt=compose_system_prompt(root),
        builtin_tools=True,
    )
